# Generated by Django 5.0.2 on 2024-03-21 02:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Profile",
        ),
    ]
