# Generated by Django 5.0.2 on 2024-03-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0002_rename_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(),
        ),
    ]
